# makeline-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
  labels:
    app: makeline-service
    part-of: bestbuy-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
      - name: makeline-service
        image: bestbuy/makeline-service:1.0
        ports:
        - containerPort: 8080
        env:
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-service-bus-secret
              key: connection-string
        - name: AZURE_SERVICE_BUS_QUEUE_NAME
          value: "orders"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/orders"
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  labels:
    app: makeline-service
    part-of: bestbuy-store
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: makeline-service
