# product-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    part-of: bestbuy-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: bestbuy/product-service:1.0
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/products"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    part-of: bestbuy-store
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: product-service
